### ISSUE TITLE
Don't include "eset" in name of SummarizedExperiment object

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BiocNYC#1]
This is confusing - make clear in words and object names that an ExpressionSet is being converted to a SummarizedExperiment:

https://github.com/waldronlab/BiocNYC/blame/master/GeneSetAnalysis.Rmd#L293

**Comment by lgeistlinger** [comment]
Yes this is part of the (currently still ongoing) transition from `ExpressionSet` to `SummarizedExperiment` in the `EnrichmentBrowser`.

That's already resolved in the `devel` vignette:

https://github.com/lgeistlinger/EnrichmentBrowser/blob/6b6d7fb5bf4eb262c2d8a33097b240519197fc77/vignettes/EnrichmentBrowser.Rnw#L188

And the workshop needs to be thoroughly overworked once the new Bioc release takes place (End of April / Begin of May)

**Comment by lgeistlinger** [comment]
Fixed in 5ebf375ad85f96ee20d18d5f9dfc672b1e47f74c
