### ISSUE TITLE
ea.browse(ora.all) not working on RStudio on Mac

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/BiocNYC#2]
Workaround is to type:

`config.ebrowser("OUTDIR.DEFAULT")`

paste the URL returned to your browser, click "reports" then "ora.html"

**Comment by lwaldron** [comment]
Note, I don't have the same issue from terminal. I think it would be more intuitive for users to place the "reports" directory in the present working directory. In any case it would be useful to `message()` the full URL to `reports/ora.html`.

**Comment by lgeistlinger** [comment]
Good point.

Hm, I just recently changed the default output directory from

```
system.file("results", package="EnrichmentBrowser")
```

to 

```
rappdirs::user_data_dir("EnrichmentBrowser")
```

Of course, the cwd is also a reasonable choice, but I thought that most users would directly interact with the html, and not care too much about the actual output files itself ... but this could be changed ...

The `message` indicating where results are located is currently only issued by the all-in-one `ebrowser` function

https://github.com/lgeistlinger/EnrichmentBrowser/blob/6b6d7fb5bf4eb262c2d8a33097b240519197fc77/R/ebrowser.R#L396

which might call `ea.browse` several times.
I'll implement a check whether `ea.browse` is called directly by the user (then `message`) or rather by `ebrowser` (then don't `message`).

**Comment by lgeistlinger** [comment]
This is fixed:

https://github.com/lgeistlinger/EnrichmentBrowser/blob/bac8f420adeb377ae6ec7ba175f34d1cb5068e3d/R/html.R#L179

Corresponding issues for `rappdirs` / `RStudio` have been opened here:

https://github.com/r-lib/rappdirs/issues/24
https://github.com/rstudio/rstudio/issues/2560
